# 27 Feb 2014 : PSW :  New
# 24 Apr 2014 : PSW :  Added .disallowed
# 07 Jul 2014 : PSW :  Added commands
# 13 Jul 2014 : PSW :  Added enchlimiter.repairs and 'el set' syntax
# 30 Jul 2014 : PSW :  Added hold,elfix.
# 18 Aug 2014 : PSW :  Removed repairs.downgrade; added enchlimiter.useillegal.

name: EnchLimiter
main: com.yahoo.phil_work.enchlimiter.EnchLimiter
version: 1.6.1
author: filbert66
description: Limits enchants by multiples or configured list
website: dev.bukkit.org/bukkit-plugins/enchlimiter
softdepend: [LanguagesAPI]
# These plugins have not updated their MaterialCategory with getRawMaterial()
loadbefore: [Thor, AntiFire, AntiCreeper]

permissions:
  enchlimiter.*:
    description: Gives access to ALL enchlimiter features
    children:
      enchlimiter.books: true
      enchlimiter.multiple: true
      enchlimiter.disallowed: true
      enchlimiter.el: true
      enchlimiter.elfix: true
  enchlimiter.books:
    description: Permits book + book enchants in anvil
    default: op
  enchlimiter.multiple:
    description: Permits multiple enchants on an enchanting table
    default: op
  enchlimiter.disallowed:
    description: Permits the disallowed enchants
    default: op
  enchlimiter.el:
    description: Permits the admin commands
    default: op
  enchlimiter.repairs:
    description: Permits repairs of illegal items
    default: op
  enchlimiter.useillegal:
    description: if 'Fix held items' is false, normally will disallow hold/equip of item unless this is true
    default: op
  enchlimiter.elfix:
    description: permits elfix command to remove disallowed enchants
    default: true
  enchlimiter.allrepairs:
    description: Permits repairs of any items, even when 'Stop all repairs' is true
    default: op
    
commands:
   el:
      description: This is the admin enchlimiter interface
      aliases: enchlimiter
      usage: /<command> reload|save|set (multiples|pickup|punish|spawns|repairs|downgrade|infinite|hold|(message [cancel|limit|disallowed])|(global anvil|table|restrictive) [true|on|false|off])
      permission: enchlimiter.el
      permission-message: You don't have <permission> 
   elfix:
     description: Removes illegal enchants from held or provided item(s)
     usage: /<command> [all|books]
     permission: enchlimiter.elfix
    
