# 27 Feb 2014 : PSW :  New
# 24 Apr 2014 : PSW :  Added .disallowed

name: EnchLimiter
main: com.yahoo.phil_work.enchlimiter.EnchLimiter
version: 0.8
author: filbert66
description: Limits multiple enchants
website: dev.bukkit.org/bukkit-plugins/enchlimiter
softdepend: [LanguagesAPI]

permissions:
  enchlimiter.*:
    description: Gives access to ALL enchlimiter features
    children:
      enchlimiter.books: true
      enchlimiter.multiple: true
      enchlimiter.disallowed: true
  enchlimiter.books:
    description: Permits book + book enchants in anvil
    default: op
  enchlimiter.multiple:
    description: Permits multiple enchants on an enchanting table
    default: op
  enchlimiter.disallowed:
    description: Permits the disallowed enchants
    default: op
