# 27 Feb 2014 : PSW :  New
# 24 Apr 2014 : PSW :  Added .disallowed
# 07 Jul 2014 : PSW :  Added commands
# 13 Jul 2014 : PSW :  Added enchlimiter.repairs and 'el set' syntax

name: EnchLimiter
main: com.yahoo.phil_work.enchlimiter.EnchLimiter
version: 1.3
author: filbert66
description: Limits enchants by multiples or configured list
website: dev.bukkit.org/bukkit-plugins/enchlimiter
softdepend: [LanguagesAPI]

permissions:
  enchlimiter.*:
    description: Gives access to ALL enchlimiter features
    children:
      enchlimiter.books: true
      enchlimiter.multiple: true
      enchlimiter.disallowed: true
      enchlimiter.el: true
  enchlimiter.books:
    description: Permits book + book enchants in anvil
    default: op
  enchlimiter.multiple:
    description: Permits multiple enchants on an enchanting table
    default: op
  enchlimiter.disallowed:
    description: Permits the disallowed enchants
    default: op
  enchlimiter.el:
    description: Permits the admin commands
    default: op
  enchlimiter.repairs:
    description: Permits repairs of illegal items
    default: op
  enchlimiter.repairs.nodowngrade:
    description: If 'Downgrade repairs' is true, it is ignored
    default: op
    
commands:
   el:
      description: This is the admin enchlimiter interface
      aliases: enchlimiter
      usage: /<command> reload|save|set (multiples|pickup|punish|spawns|repairs|downgrade|(message [cancel|limit|disallowed]) [true|on|false|off])
      permission: enchlimiter.el
      permission-message: You don't have <permission>
